WebAppGenerator/Controllers/GeneratorController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mainhub.Tools.WebAppGenerator.Controllers
{
    /// <summary>
    /// 
    /// TYPES:
    ///     -MVC USING NUGET PACKAGES WITH MAIN C# CODE WRITTEN
    ///     -TEMPLATES IS NORMAL MVC NO EXTRA PACKAGES INSTAL
    ///     -CMS USUAL CMS(YET TO DEFINE)
    /// 
    /// </summary>
    public class GeneratorController : Controller
    {
        public ActionResult Generate()  
        {
            return View("Generate","_Layout");
        }
        public string Create(string name, string type, string path, bool modular, bool run)
        {
            //type mvc vao incluir packages jafeitos
            string feedbackMessage = "Created succesfully";
            Process process = new Process();
            if (modular && type.ToLower() == "mvc")
            {
                process.StartInfo.FileName = "cmd.exe";
                process.StartInfo.CreateNoWindow = false;
                process.StartInfo.RedirectStandardInput = true;
                process.StartInfo.RedirectStandardOutput = true;
                process.StartInfo.UseShellExecute = false;
                process.Start();
                process.StandardInput.WriteLine($"cd \"{path}\"");
                process.StandardInput.WriteLine("dotnet new -i OrchardCore.ProjectTemplates::1.0.0-*");
                process.StandardInput.WriteLine($"dotnet new oc{type} -n \"{name}\"");
                process.StandardInput.WriteLine($"dotnet new ocmodulemvc -n \"{name}Module\"");
                process.StandardInput.WriteLine($"dotnet add {name} reference {name}Module");
                if (run)
                {
                    process.StandardInput.WriteLine($"dotnet run --project {type}\\{name}\\{name}.csproj");
                }
                process.StandardInput.Flush();
                process.StandardInput.Close();
            }
            else if (!modular && type.ToLower() == "mvc")
            {
                process.StartInfo.FileName = "cmd.exe";
                process.StartInfo.CreateNoWindow = false;
                process.StartInfo.RedirectStandardInput = true;
                process.StartInfo.RedirectStandardOutput = true;
                process.StartInfo.UseShellExecute = false;
                process.Start();
                process.StandardInput.WriteLine($"cd \"{path}\"");
                process.StandardInput.WriteLine("dotnet new -i OrchardCore.ProjectTemplates::1.0.0-*");
                process.StandardInput.WriteLine($"dotnet new oc{type} -n \"{name}\"");
                if (run)
                {
                    process.StandardInput.WriteLine($"dotnet run --project {path}\\{name}\\{name}.csproj");
                }
                //process.StandardInput.Flush();
                //process.StandardInput.Close();
            }
            else if (modular && type.ToLower() == "template")
            {
                process.StartInfo.FileName = "cmd.exe";
                process.StartInfo.CreateNoWindow = false;
                process.StartInfo.RedirectStandardInput = true;
                process.StartInfo.RedirectStandardOutput = true;
                process.StartInfo.UseShellExecute = false;
                process.Start();
                //VALIDATE PATH
                process.StandardInput.WriteLine($"cd \"{path}\"");
                process.StandardInput.WriteLine("dotnet new -i OrchardCore.ProjectTemplates::1.0.0-*");
                process.StandardInput.WriteLine($"dotnet new ocmvc -n \"{name}\"");
                process.StandardInput.WriteLine($"dotnet new ocmodulemvc -n \"{name}Module\"");
                process.StandardInput.WriteLine($"dotnet add \"{name}\" reference \"{name}Module\"");
                if (run)
                {
                    process.StandardInput.WriteLine($"dotnet run --project {path}\\{name}\\{name}.csproj");
                }
                process.StandardInput.Flush();
                process.StandardInput.Close();
                Console.WriteLine(process.StandardOutput.ReadToEnd());
                process.StandardOutput.Close();
            }
            else if (!modular && type.ToLower() == "template")
            {
                process.StartInfo.FileName = "cmd.exe";
                process.StartInfo.CreateNoWindow = false;
                process.StartInfo.RedirectStandardInput = true;
                process.StartInfo.RedirectStandardOutput = true;
                process.StartInfo.UseShellExecute = false;
                process.Start();
                process.StandardInput.WriteLine($"cd \"{path}\"");
                process.StandardInput.WriteLine("dotnet new -i OrchardCore.ProjectTemplates::1.0.0-*");
                process.StandardInput.WriteLine($"dotnet new ocmvc -n \"{name}\"");
                if (run)
                {
                    process.StandardInput.WriteLine($"dotnet run --project {path}\\{name}\\{name}.csproj");
                }
                process.StandardInput.Flush();
                process.StandardInput.Close();
            }
            else if(modular && type.ToLower() == "cms")
            {
                process.StartInfo.FileName = "cmd.exe";
                process.StartInfo.CreateNoWindow = false;
                process.StartInfo.RedirectStandardInput = true;
                process.StartInfo.RedirectStandardOutput = true;
                process.StartInfo.UseShellExecute = false;
                process.Start();
                process.StandardInput.WriteLine($"cd \"{path}\"");
                process.StandardInput.WriteLine("dotnet new -i OrchardCore.ProjectTemplates::1.0.0-*");
                process.StandardInput.WriteLine($"dotnet new oc{type} -n \"{name}\"");
                process.StandardInput.WriteLine($"dotnet new ocmodulecms -n \"{name}Module\"");
                process.StandardInput.WriteLine($"dotnet add {name} reference {name}Module");
                if (run)
                {
                    process.StandardInput.WriteLine($"dotnet run --project {path}\\{name}\\{name}.csproj");
                }
                process.StandardInput.Flush();
                process.StandardInput.Close();
            }
            else if (!modular && type.ToLower() == "cms")
            {
                process.StartInfo.FileName = "cmd.exe";
                process.StartInfo.CreateNoWindow = false ;
                process.StartInfo.RedirectStandardInput = true;
                process.StartInfo.RedirectStandardOutput = true;
                process.StartInfo.UseShellExecute = false;
                process.Start();
                //Get path to install the webapp
                process.StandardInput.WriteLine($"cd \"{path}\"");
                process.StandardInput.WriteLine("dotnet new -i OrchardCore.ProjectTemplates::1.0.0-*");
                process.StandardInput.WriteLine($"dotnet new oc{type} -n \"{name}\"");
                if (run)
                {
                    process.StandardInput.WriteLine($"dotnet run --project {path}\\{name}\\{name}.csproj");
                }
                process.StandardInput.Flush();
                process.StandardInput.Close();
            }
            return feedbackMessage;
        }
    }
}

WebAppGenerator/Views/Generator/Generate.cshtml
@{
    ViewBag.Title = "Generate";
}
<h2 class="text-center" style="font-size: 80px;">Generate Application</h2>
<!--Add additional information on a modal.-->
<div class="container" style=" margin-top: 120px; margin-bottom: 100px;">
    <div class="row">
        <div class="col-md-4">
            <div class="row">
                <div class="col-md-12">
                    <div class="label label-info col-md-12" style="text-align:center; height: 60px; margin-left:2%">
                        <h4><b>TEMPLATE</b></h4>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="col-md-4" style="padding:0px; margin-left: 40%; margin-right: 40%; ">
                        <button class="bt btn btn-danger btn-lg" data-toggle="modal" data-target="#modalId" value="template">Create</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="row">
                <div class="col-md-12">
                    <div class="label label-info col-md-12" style="text-align:center; height: 60px; margin-left:2%">
                        <h4><b>MVC</b></h4>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="ol-md-4" style="padding:0px; margin-left: 40%; margin-right: 40%">
                        <button class="bt btn btn-danger btn-lg" data-toggle="modal" data-target="#modalId" value="mvc">Create</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="row">
                <div class="col-md-12">
                    <div class="label label-info col-md-12" style="text-align:center; height: 60px;margin-left:2%">
                        <h4><b>CMS</b></h4>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="ol-md-4" style="padding:0px; margin-left: 40%; margin-right: 40%;">
                        <button class="bt btn btn-danger btn-lg" data-toggle="modal" data-target="#modalId" value="cms">Create</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--Form to install app inside modal-->
<div id="modalId" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title offset-md-3">Cria a tua aplicação</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <div class="container">
                    <form id="generator" hidden>
                        <h3>Detalhes da Aplicação:</h3><br />
                        <div class="form-group">
                            <label for="name">Nome:</label>
                            <input id="name" class="form-control col-md-9" type="text" value="" name="name" placeholder="Nome da aplicação" /><br />
                            <label for="type">Tipo:</label>
                            <input id="type" class="form-control col-md-9" type="text" value="" name="type" disabled /><br />
                            <label for="path">Caminho:<small id="pathHelp" class="form-text text-muted">(Caminho para instalar aplicação a ser gerada)</small></label>
                            <input id="path" class="form-control col-md-9" type="text" value="" name="path" aria-describedby="pathHelp" /><br />
                            <label for="modular">Pretende uma aplicação modular?</label>&nbsp;
                            <input id="modular" type="checkbox" name="modular" /><br />
                            <label for="run">Pretende inicializar a aplicação?</label>
                            <input id="run" type="checkbox" name="run" />
                        </div>
                    </form>
                </div>
            </div>
            <div class="modal-footer" style="margin-bottom: 0.6%;">
                <input class="btn btn-primary" id="submit" style="margin-right: 58%;" type="submit" value="Criar" data-dismiss="modal" />
                <button type="button" class="btn btn-danger col-md-3" data-dismiss="modal">Cancelar</button>
            </div>
        </div>
    </div>
</div>

<style>
    fieldset {
        display: block;
        margin-left: 2px;
        margin-right: 2px;
        padding-top: 0.35em;
        padding-bottom: 0.625em;
        padding-left: 0.75em;
        padding-right: 0.75em;
        border: 2px groove;
    }

    input {
        margin-left: 2%;
        margin-bottom: 2%;
    }
</style>
<script src="~/Content/vendor/jquery/jquery.min.js"></script>
<script>
    $(".bt").on("click", function () {
        $("#generator").removeAttr("hidden");
        var s = $(this).attr("value");
        $("#type").attr("value", s);

    });
</script>
<script>
    $("#submit").on("click", function (e) {
        e.preventDefault();
        var name = $("#name").val();
        var type = $("#type").attr("value");
        var path = $("#path").val();
        var modular;
        var run;
        if ($("input[id='modular']:checked").val() == "on") {
            modular = true;
        } if ($("input[id='modular']:checked").val() == undefined) {
            modular = false;
        }
        if ($("input[id='run']:checked").val() == "on") {
            run = true;
        } if ($("input[id='run']:checked").val() == undefined) {
            run = false;
        }
        $.post("https://localhost:44330/Generator/Create", { name: name, type: type, path: path, modular: modular, run: run },
            function (r) {
                alert(r);
                console.log(r);
            });
    });
</script>

WebAppGenerator/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Generator Tool - Mainhub</title>
    <link href="~/Content/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/css/scrolling-nav.css" rel="stylesheet">
</head>
<body id="page-top">
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand js-scroll-trigger" href="@Url.Action("Generate","Generator")">Mainhub</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="#services">Serviços</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="#contact">Contactos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="~/Generator/Generate">Gerador</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <header class="bg-primary text-white" style="height: 40px; padding-top: 100px;">
        <div class="container text-center">
            <h1></h1>
            <p class="lead">Web Application Automatization Tool</p>
        </div>
    </header>
    <section class="bg-light" style="padding-bottom: 10px; padding-top: 100px;">
        @RenderBody()
    </section>
    <section id="services" class="bg-light">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <h2>Services we offer</h2>
                    <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut optio velit inventore, expedita quo laboriosam possimus ea consequatur vitae, doloribus consequuntur ex. Nemo assumenda laborum vel, labore ut velit dignissimos.</p>
                </div>
            </div>
        </div>
    </section>
    <section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <h2>Contact us</h2>
                    <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero odio fugiat voluptatem dolor, provident officiis, id iusto! Obcaecati incidunt, qui nihil beatae magnam et repudiandae ipsa exercitationem, in, quo totam.</p>
                </div>
            </div>
        </div>
    </section>
    <!-- Footer -->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Your Website 2019</p>
        </div>
        <!-- /.container -->
    </footer>
    <script src="~/Content/vendor/jquery/jquery.min.js"></script>
    <script src="~/Content/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/Content/vendor/jquery-easing/jquery.easing.min.js"></script>
    <script src="~/Content/js/scrolling-nav.js"></script>
</body>
</html>